title: Koding Custom Billing
email: support@koding.com
repository: koding/on-prem-payment
description: >
  Online payments for custom or on-prem billing.
url: "https://cc.koding.com"
# url: "dev.koding.com:4000"
timezone: America/Los_Angeles
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
sass:
  style: compressed
  sass_dir: _css
